### ISSUE TITLE
No way to run clustering without edge attribute

### ISSUE THREAD

**Issue by risserlin** [BaderLab/AutoAnnotateApp#10]
Currently when you select a clustering algorithm you have to select an edge attribute to cluster with.  Would be good to be able to cluster with just the edge irrespective of the weight of the edge.

**Comment by mikekucera** [comment]
54b6e30ab8a11176231adf579a44d60be2f75416

**Comment by mikekucera** [comment]
Something strange is going on. The edge weight attribute doesn't seem to have an effect when used in a command. I will need to take a closer look at how clusterMaker works in this regard.

**Comment by mikekucera** [comment]
Also clusterMaker does not list List columns, so we shouldn't list them either.
