### ISSUE TITLE
reload annotated session and no annotations present in AA panel

### ISSUE THREAD

**Issue by risserlin** [BaderLab/AutoAnnotateApp#102]
<img width="1029" alt="screen shot 2017-07-20 at 6 20 53 pm" src="https://user-images.githubusercontent.com/3842763/28441325-33f6f85e-6d78-11e7-9f47-cfb341ec9aee.png">

link to the session:
https://www.dropbox.com/s/k3lb2glqhxusnzg/EM_gsea_results_annotated.cys?dl=0

**If this session is not salvageable I might cry ...**

**Comment by mikekucera** [comment]
Do you have the STRING app installed?

**Comment by risserlin** [comment]
YES!  uninstalling String fixed it.

**Comment by mikekucera** [comment]
EM had the same issue
https://github.com/BaderLab/EnrichmentMapApp/issues/237
