### ISSUE TITLE
Change wording on interface

### ISSUE THREAD

**Issue by risserlin** [BaderLab/AutoAnnotateApp#103]
word "cluster" might be confusing to basic user in the "quick start" tab.  

Suggest changing:
"Max number of clusters" to "Max number of annotations"
Add a tooltip too - "Annotate only the top X largest clusters in the network"

"Cluster all nodes" to "Annotate entire network"

Also, maybe set the default to the entire network?

**Comment by risserlin** [comment]
tool tip for "Max number of annotations" is on the wrong option.

**Comment by mikekucera** [comment]
whoops
