### ISSUE TITLE
hide labels select and move a cluster and label re-appears

### ISSUE THREAD

**Issue by risserlin** [BaderLab/AutoAnnotateApp#107]
hide labels.
select a cluster and move and the label will reappear.
If you unclick hide labels and reclick you can re-hide it but if you move it again the same thing happens.
<img width="760" alt="screen shot 2017-08-04 at 11 39 30 am" src="https://user-images.githubusercontent.com/3842763/28975888-c025fc7a-7909-11e7-8e0a-e621941242e9.png">

**Comment by mikekucera** [comment]
This works for me. Ruth can you please try again to see if you can reproduce it.

**Comment by risserlin** [comment]
Thanks.  I can't reproduce this in the latest version.
