### ISSUE TITLE
Hidden labels and annotations still present in exported PDF

### ISSUE THREAD

**Issue by risserlin** [BaderLab/AutoAnnotateApp#108]
hide labels and hide boxes
export image.
in the exported image the shapes are still visible.  The labels are not visible but they are there when you select all the objects. 
![em_results_small](https://user-images.githubusercontent.com/3842763/28976989-29975d1c-790e-11e7-926b-9a106b2f8b5e.png)

**Comment by mikekucera** [comment]
Hiding labels and shapes doesn't remove the annotations. It sets the label font size to 0 and the annotation to fully transparent. When the network view is exported to PDF the labels and shapes are still present (they are selectable). 

Also I sometimes get an error about font size of 0 not being supported by the pdf writer.

**Comment by mikekucera** [comment]
I don't want to actually delete the annotations as that is much more heavyweight, it fires lots of events, and it will probably lead to other bugs. The best thing might be to fix this in Cytoscape.

**Comment by mikekucera** [comment]
Fixed in Cytoscape 3.9.
