### ISSUE TITLE
AA label width?

### ISSUE THREAD

**Issue by veroniquevoisin** [BaderLab/AutoAnnotateApp#117]
I probably reported it already but again as I would find it very useful to create a figure. Would it be possible to adjust AA label width the same way as it can be done for node labels? 
![screen shot 2018-01-10 at 10 39 56 am](https://user-images.githubusercontent.com/7570379/34781054-d3f9dbfc-f5f2-11e7-8123-817b37b0c7ab.png)

**Comment by mikekucera** [comment]
Added word wrap.
