### ISSUE TITLE
make AutoAnnotate open Wordcloud automatically

### ISSUE THREAD

**Issue by veroniquevoisin** [BaderLab/AutoAnnotateApp#118]
what about making AA  open WordCloud automatically?
 * to be able to adjust other options like  excluding additional words
 * WC output will be displayed when we select nodes and it add information to the content of the clusters 
 * make it easier to understand/explain how AA is creating the labels
![screen shot 2018-01-10 at 11 55 59 am](https://user-images.githubusercontent.com/7570379/34784782-43898f1c-f5fd-11e7-80d5-655af601530d.png)

**Comment by mikekucera** [comment]
AA has the ability to open the Delimiters and Excluded Words dialogs from WordCloud. The AA docs explain how to use WordCloud.
