### ISSUE TITLE
"hiding labels' and exporting image as pdf: got an error "font size too small"

### ISSUE THREAD

**Issue by veroniquevoisin** [BaderLab/AutoAnnotateApp#120]
I  m not able to export the map as pdf when the option "hiding labels" is checked. I get the error "font size too small". It works when I uncheck the box. 
<img width="1379" alt="screen shot 2018-01-23 at 9 58 05 am" src="https://user-images.githubusercontent.com/7570379/35282764-4e779c1c-0024-11e8-9018-ea2acfda7f7f.png">

**Comment by mikekucera** [comment]
How exactly are you exporting the map? Export network to image pdf seems to work.

**Comment by mikekucera** [comment]
Can't reproduce this.
