### ISSUE TITLE
stored session: cannot play with the "Autoannotate display"

### ISSUE THREAD

**Issue by veroniquevoisin** [BaderLab/AutoAnnotateApp#121]
I reopen  a stored session containing annotations . I cannot change any style using the "AutoAnnotate display"
![screen shot 2018-01-30 at 11 21 22 am](https://user-images.githubusercontent.com/7570379/35577684-19c58b32-05b0-11e8-8c40-26817abf1f06.png)

**Comment by mikekucera** [comment]
Can you send me the session file please.
