### ISSUE TITLE
autoannotate summary does not work through cyrest

### ISSUE THREAD

**Issue by risserlin** [BaderLab/AutoAnnotateApp#126]
It works when you call it from the command line window but when I make the same call from R using RCy3 commandsGET all I get is:
[1] "Available arguments for 'autoannotate summary':"

And no command is run.

**Comment by mikekucera** [comment]
As a workaround add network=current to the url.
eg)
http://localhost:1234/v1/commands/autoannotate/summary?network=current

I'm still going to look into why CyREST is doing that, because that argument should be optional.

**Comment by risserlin** [comment]
I tried that and it still didn't work but I will try again.  I think I actually used the network suid and it didn't work.

**Comment by risserlin** [comment]
I got it to work.  I was missing quotes around "current".

**Comment by mikekucera** [comment]
I filed a bug against CyREST:
http://code.cytoscape.org/redmine/issues/4240
