### ISSUE TITLE
Layout clusters to prevent overlap.

### ISSUE THREAD

**Issue by mikekucera** [BaderLab/AutoAnnotateApp#130]
One of the major complaints about AA is that after clustering and annotating the network looks very messy. It takes a lot of work to manually lay out the network to make it look nice.

We need a new layout algorithm or capability that prevents the clusters from overlapping. There is already the ability to do this but the results are unsatisfactory, so we will need a better algorithm. Really it just has to move the clusters so that they respect each others "personal space". Perhaps a force directed layout where each cluster is treated as a unit will work.

**Comment by Niveda-S** [comment]
Is this option available for command line using the REST API? I see that the prevent clusters overlap option is available in the GUI, but I'm unable to replicate it via command-line.
