### ISSUE TITLE
Is there a margin around the annotations?

### ISSUE THREAD

**Issue by risserlin** [BaderLab/AutoAnnotateApp#134]
When generating figures from EMs that have annotations in graphic/illustrator I have to tighten all my annotation circles to make the image cleaner.  I was wondering if there is currently some sort of margin or padding added to each circle that the user can potentially control.

**Comment by mikekucera** [comment]
There is some padding. I cannot be controlled currently. 

The algorithm that determines the shape of the annotation is pretty clunky actually.
