### ISSUE TITLE
exclusion of words 

### ISSUE THREAD

**Issue by veroniquevoisin** [BaderLab/AutoAnnotateApp#135]
when I autoannotate a map, I often realize that I have to exclude words like 'negative' 'positive' 'hallmark', etc to get more informative labels , I have to open WordCloud for that although I m using AutoAnnotate . I think it is not very intuitive that's why a while ago I had suggested that WordCloud opens automatically when AA is used so that we can use all functions but I' not sure.
Would it better to add a  'add word(s) to be excluded' as an AA parameter?
 
![screen shot 2018-10-05 at 2 51 30 pm](https://user-images.githubusercontent.com/7570379/46554431-368ee800-c8ae-11e8-951a-fa18bfa5dc42.png)

**Comment by veroniquevoisin** [comment]
re-emphasizing this request based on my recent use of autoannotate. I get more precise annotations if I remove general word like 'regulation', 'pathway', 'positive', 'signaling', etc,... I need to open wordcloud for it and it is not intuitive for users who don't know that autoannotate is using wordcloud. Can we get the word removing as an AA parameter?

**Comment by mikekucera** [comment]
yes

**Comment by mikekucera** [comment]
Fixed in commit 8d8057cb22dfa4bf9c65a9cdb63fb454f1562adb and 6cf317741218c51bf4a83b7bd8c2bdd484c64f06
