### ISSUE TITLE
install from github

### ISSUE THREAD

**Issue by zeneofa** [BaderLab/AutoAnnotateApp#136]
The current version in the cytoscape app store was updated on Sep 2017. There have been a number of fixes since then, how do I install the latest master branch from git?

**Comment by mikekucera** [comment]
We will be releasing the new version of AutoAnnotate in November right after Cytoscape 3.7 is released. I do not recommend creating your own build from the master branch as it is not fully tested yet. 

If you really want the latest code you can download the repository and run the maven build, that will created a jar file that you can then copy into the `CytoscapeConfiguration/3/apps/installed` folder.
