### ISSUE TITLE
Layout clusters to prevent overlap via command-line

### ISSUE THREAD

**Issue by Niveda-S** [BaderLab/AutoAnnotateApp#140]
Is this option available for command line using the REST API? I see that the prevent clusters overlap option is available in the GUI, but I'm unable to replicate it via command-line.

**Comment by mikekucera** [comment]
There is a command `autoannotate layout` but it only runs the older grid style layout. The newer CoSE layout is not available from this command.

I should add an argument to the `autoannotate layout` command that lets you specify which layout to run.

**Comment by Niveda-S** [comment]
That would be great, thanks a lot!

**Comment by Niveda-S** [comment]
Hey, I was wondering if you had a chance to add the argument for the autoannotate layout?

**Comment by mikekucera** [comment]
Hi Niveda,

Can you try this build and let me know if it works for you. 
https://github.com/BaderLab/AutoAnnotateApp/releases/tag/release%2Fv1.3.1

You can run the Cose layout like this: `autoannotate layout layout=cose`

If you are satisfied with the fix then I can upload this new version to the app store.
