### ISSUE TITLE
Scale font by cluster: reduce the difference between min and max size

### ISSUE THREAD

**Issue by veroniquevoisin** [BaderLab/AutoAnnotateApp#141]
keep the scale but make the smallest font size larger to diminish the difference between small and large clusters so that all labels are readable . 
![screen shot 2019-03-07 at 1 22 26 pm](https://user-images.githubusercontent.com/7570379/53979724-89c6ca00-40dc-11e9-8346-a8e2f4d7e372.png)

**Comment by mikekucera** [comment]
I added a "min font size" slider so that labels can't get too small.

Also in Cytoscape 3.9 the renderer will support HiDPI displays, which makes it much easier to read small labels.
