### ISSUE TITLE
Annotation Names

### ISSUE THREAD

**Issue by AshleyHeinson** [BaderLab/AutoAnnotateApp#142]
Dear Sir / Madam, 

I am having a little trouble interpreting the output of the AutoAnnotate tool after applying the EnrichmentMap software in Cytoscape. It mostly works great, but I have a few annotations that are giving me trouble such as returning: "cards http gsea"or "cards broadinstitute http" as cluster names. How should I interpret these? Is there a way that I can get a list of all possible annotations from this software as perhaps I would be able to see where these come from a bit more clearly. 

Thank you very much for your help and your software, it is proving very useful. 

Ashley

**Comment by risserlin** [comment]
Hi Ashley, 
To change those labels you need to add them to the word exclusion list.  Wordcloud that computes the labels used by auto annotate keeps a list of words to ignore when computing the label. We have put a lot of common words there but sometimes depending on the datasource there might be new words that need to be added.   Are you using gene cards? or are these genesets from MSigDB?

To add words to the list:
Open Wordcloud : Apps -> Wordcloud -> Show Wordcloud
Click on advanced in wordcloud panel to expand
Click on "Excluded words" button
Add words individually to the list (http, gsea, cards, broadinstitute)
once you have added the words you should see them under Added words
In auto-annotate panel under the menu button (three lines on the right hand side of the panel) select "Recalculate labels..."
If you haven't annotated your network yet then you can just annotate it at this point. 

Unfortunately these added words won't be saved between sessions.  

Ruth

**Comment by AshleyHeinson** [comment]
Dear Ruth,

Thank you very much for the quick response. I will implement this as you have proposed. 

Ashley

**Comment by mikekucera** [comment]
Related to #135
