### ISSUE TITLE
enhancement: be able to autoannotate on selected nodes only

### ISSUE THREAD

**Issue by veroniquevoisin** [BaderLab/AutoAnnotateApp#143]
enhancement: be able to autoannotate on selected nodes only

**Comment by veroniquevoisin** [comment]
or to exclude some nodes by selecting them (eg EM post analysis nodes)

**Comment by mikekucera** [comment]
I've looked into this in the past. The problem is that clusterMaker does not support clustering only selected nodes. 

As a workaround I recommend to create a new network from the selected nodes and run autoannotate on that.
