### ISSUE TITLE
Fetch nodes belonging to AutoAnnotate clusters via CyREST API

### ISSUE THREAD

**Issue by rosscm** [BaderLab/AutoAnnotateApp#146]
Possibility for an operation to fetch node names belonging to clusters generated by AutoAnnotate?

**Comment by risserlin** [comment]
Hi Catherine, 
This is a mutlistep process but it is doable from the Cyrest API.  Are you doing this in R or from somewhere else?  Also, I wrote my code a while ago so I am not sure if there are new functions in autoannotate in order to do this directly. 

In R you need to:
1. cluster the network,
2. Get all the cluster annotations from cytoscape.
3. then call autoannotate for each of the clusters to get the label for that cluster.  
4. collate all the results as you go through the network 

The example below was using an enrichment map where each node is a geneset, hence the names.  
It requires the RCy3 package.  

The same logic should work for other environments. 

    #cluster the network
    clustermaker_url <- paste("cluster mcl attribute=", similarity_attrib," network=SUID:",network_suid, sep="")
    commandsGET(clustermaker_url)
  
    #after clustering get node and edge table that will have the cluster annotations
    default_node_table <- getTableColumns(table= "node",network = network_suid)
    default_edge_table <- getTableColumns(table="edge",network = network_suid)
  
    #get all the cluster numbers
    clusternumbers <- default_node_table$'__mclCluster'
  
    #get the unique set of clusters
    set_clusters <- unique(clusternumbers)
    #only include clusters that aren't zero.  
    set_clusters <- set_clusters[which(set_clusters != 0)]
  
    #calculate the cluster names using auto annotate and collate all the nodes associated 
    #with each cluster
    cluster_names <- c()
  
    for(i in 1:length(set_clusters)){
    
      current_cluster <- set_clusters[i]
   
      gs_in_cluster <- default_node_table$name[which(default_node_table$'__mclCluster' == current_cluster)]
    
      #for this cluster of gs get the gs descr to use in defining in autoannotate
      gs_in_cluster_suid <-  default_node_table$SUID[which(default_node_table$name %in% gs_in_cluster)]
      suids_aa <- paste("SUID", gs_in_cluster_suid,sep=":")
    
      #get the annotation for the given cluster
      curernt_name = NULL
      aa_label_url <- paste("autoannotate label-clusterBoosted labelColumn=", descr_attrib," maxWords=3 nodeList=\"",paste(suids_aa,collapse=","),"\"", sep="")
      current_name <-commandsGET(aa_label_url)
    
      cluster_names <- rbind(cluster_names, c(current_cluster,current_name, length(gs_in_cluster),
                                            paste(gs_in_cluster,collapse=";")))
    
    }

**Comment by rosscm** [comment]
Thanks Ruth. Yes I'm doing this in R.
There are a couple undefined variables in your code, namely `similarity_attrib` and `descr_attrib`. How are those defined?

**Comment by risserlin** [comment]
sorry forgot to include those lines: 
I am using this for an enrichment map so I use the edge attribute that contains "similarity coefficient" in the name (for different enrichment maps this attribute might have a different prefix like EM1 or EM2 so I check what it is called in the current netowrk).  Same applies for the descr_attrib which I grab the node name that has "GS_DESCR"

  #get the correct attribute names
  similarity_attrib <- edgetable_colnames[grep(edgetable_colnames, pattern = "similarity_coefficient")]
  
   #get the column from the nodetable and node table
   nodetable_colnames <- getTableColumnNames(table="node",  network = network_suid)
  
   descr_attrib <- nodetable_colnames[grep(nodetable_colnames, pattern = "GS_DESCR")]

**Comment by rosscm** [comment]
works as needed now, thanks again
