### ISSUE TITLE
mcl cluster: granularity parameter (inflatation value)

### ISSUE THREAD

**Issue by veroniquevoisin** [BaderLab/AutoAnnotateApp#147]
one parameter that I use quite often to fine tune autoannotate clusters and labels is the mcl cluster granularity parameter. I'm wondering if this could be also included in the autoannotate advanced parameters 

![Screen Shot 2019-10-11 at 9 42 05 AM](https://user-images.githubusercontent.com/7570379/66656480-148c1c00-ec0c-11e9-84a4-4a1eb247e25b.png)

**Comment by mikekucera** [comment]
I attempted to make this work but no dice. The granularity parameter is a tunable field that is internal to clusterMaker's MCLClusterTask. There is no way to directly read/write it through API. I tried to create a UI for the tunables using the TunableMutator API but that didn't work. So unfortunately the only way to set this parameter is through the clusterMaker UI.
