### ISSUE TITLE
Collapse all restructures network layout

### ISSUE THREAD

**Issue by gaelanm** [BaderLab/AutoAnnotateApp#148]
Hello,

I am using AutoAnnotate to create some clustered themes from a gene set I have. I have gone through and reorganized the clusters for a more visually appealing design. I want to collapse the clusters into a single node for easier reading, however, AutoAnnotate restructures my network following collapse all which causes a lot of the cluster nodes to seemingly form/lose new edges, and many of the cluster nodes are overlapped in the centre of the network.

I am using Cytoscape 3.7.2 and the latest version of AutoAnnotate. Any help would be great!

**Comment by mikekucera** [comment]
Unfortunately there is not much we can do about this. Collapsing clusters in cytoscape changes the topology of the network and creates "meta-edges" between the collapsed nodes.

You can try generating a summary network instead (available in the AutoAnnotate panel menu). Its very similar in concept but it generates a new network and keeps your original network intact.

**Comment by gaelanm** [comment]
Ah, that is unfortunate. Thank you very much for your response!

Gaelan
________________________________
