### ISSUE TITLE
autoannotate option returnJsonOnly=true returns nothing

### ISSUE THREAD

**Issue by risserlin** [BaderLab/AutoAnnotateApp#149]
Running the following command:
autoannotate annotate-clusterBoosted returnJsonOnly=true
on an existing annotated EM or a non-annotated EM doesn't return anything.

**Comment by mikekucera** [comment]
It depends on how you call it. The JSON is returned if you call it as a POST through CyRest. If you just run the command in the command panel it does not show the results. This can easily be fixed though.
