### ISSUE TITLE
"Ghost" annotate cluster bubbles

### ISSUE THREAD

**Issue by shraddhapai** [BaderLab/AutoAnnotateApp#151]
Hi, 
I used RCy3 to generate an EnrichmentMap, apply AutoAnnotate to the resulting network, and apply a layout-by-cluster operation. In Cytoscape, I then manually unchecked "Scale font by cluster size". When I then select clusters and move them to a different location, there are still yellow bubbles and shadows of the previous label left behind. 

In the screenshot attached, you can see the bubbles at the end of row 2 (the corresponding clusters were moved to create a new third row).

![Screen Shot 2020-02-12 at 11 10 20 AM](https://user-images.githubusercontent.com/7502338/74354405-4f07f000-4d89-11ea-9bc6-d6a0c793e0cd.png)

These labels persist even after deleting the Cluster Annotation Set in the left-hand panel, infact across the entire network (not just the moved nodes), suggesting that the entire AutoAnnotate layer is affected by this lack of refreshing. The outdated graphics persist even after saving the session, exiting Cytoscape and reopening the session anew. So refreshing doesn't appear to fix the problem.

![Screen Shot 2020-02-12 at 11 18 32 AM](https://user-images.githubusercontent.com/7502338/74354481-6ba42800-4d89-11ea-824e-eabea8deafc1.png)

Updating to AutoAnnotate 1.3.2 did not resolve this problem.
I'm using EnrichmentMap 3.1.0 and Cytoscape 3.7.2.

Thanks!

**Comment by mikekucera** [comment]
Try going to the Annotation panel and deleting the annotations there. Then recreate the annotation set.

**Comment by apostonaut** [comment]
I have also experienced these "ghost" annotations. I clicked "refresh" (i.e. the circular arrow button next to the "+" button in the AutoAnnotate pane, as can be seen in Shraddha's post above), and it doubled all my annotations, with no way to undo.

**Comment by nanderthol** [comment]
I get this all the time. It's a major pain. Once it happens the first time, it seems to happen repeatedly. I have to quit out and build new networks a lot. Using cytoscape 3.8.2 with autoannotate 1.3.3 and enrichment map 3.3.1. On a mac - but this thing is java right, so shouldn't matter what platform???

**Comment by mikekucera** [comment]
I'm not sure why the "ghost" annotations are left behind. It must be a bug in Cytoscape. As a workaround I enhanced the "Redraw Clusters" task (ie the "refresh" button) to delete all annotations created by AA every time its run. That should clean up the ghost annotations.
