### ISSUE TITLE
My entire network annotated was deleted

### ISSUE THREAD

**Issue by apostonaut** [BaderLab/AutoAnnotateApp#152]
I am unsure why. I am very certain that I did not accidentally delete it. AutoAnnotate was having difficulty loading all the graphic details of my network due to limited RAM on my machine. I then saved my .cys session, with the "incompletely visible" annotated network on my screen (i.e. I clicked "Show Graphic Details", and not all graphic details were able to be shown. many edges and labels were not drawn on my screen). I then opened my .cys file the next day, and the "incompletely visible" annotated network was no longer among my datasets.

I admit that the 4G of RAM on my machine seems to not be enough to run AutoAnnotate. However, I feel that this is a pretty serious result from having limited RAM.

**Comment by risserlin** [comment]
HI Michael, 
Are there any errors coming up in your command window when you reload your cytoscape session? Can you attach your session here or send it to me or mike to see if it is rescuable?
Thanks, 
Ruth 
(send it to me and I will see if I can rescue it.)
