### ISSUE TITLE
Not showing new columns in dropdown to select user-defined clusters

### ISSUE THREAD

**Issue by risserlin** [BaderLab/AutoAnnotateApp#153]
created network
loaded in externally defined cluster numbers through file -> load table
opened autoannotate (*not sure if I opened it before I loaded in the new attribute)
tried to use the loaded in defined clusters but it wasn't in the list of available attributes to use

How to get around it:
tried renaming the column to get AA to recognize the new column.  - didn't work
saved session and reloaded and open AA and the attribute was then there in the list

**Comment by mikekucera** [comment]
Duplicate of #160
