### ISSUE TITLE
autoannotate layout command

### ISSUE THREAD

**Issue by risserlin** [BaderLab/AutoAnnotateApp#154]
add the ability to layout just the set of selected node.

**Comment by mikekucera** [comment]
I registered the CoSE layout as a normal Cytoscape layout. It can now be executed on selected nodes using the 'layout' command.

`layout autoannotate-cose-cluster nodeList="selected"`

**Comment by mikekucera** [comment]
You can also tune the layout using the CoSE layout parameters.
