### ISSUE TITLE
Add ability to provide user assigned clusters to label-clusterBoosted

### ISSUE THREAD

**Issue by s2hui** [BaderLab/AutoAnnotateApp#155]
Please add the ability for users to provide or use their own assigned clusters to label-clusterBoosted function?  Functionality would be like what exists in annotate-clusterBoosted method with parameters:

- clusterIdColumn=<String>:  Name of node column to use to identify clusters when the 'userClusterMaker' argument is false.  and 
- useClusterMaker=true|false: If true calls the clusterMaker app to generate the clusters (default). If false uses the 'clusterIdColumn' parameter to identify clusters.

thanks

**Comment by mikekucera** [comment]
I believe this functionality already exists (it was added for issue #110).

The `annotate-clusterBoosted` command has a parameter `returnJsonOnly` that when set to true will return the list of labels as a JSON structure and will not actually create the annotations. You can use the `returnJsonOnly` argument in conjunction with `useClusterMaker=false` and `clusterIdColumn="label_column"`.
