### ISSUE TITLE
Layout Clusters

### ISSUE THREAD

**Issue by pillepalle123** [BaderLab/AutoAnnotateApp#162]
super helpful app! thx
I was wondering if there are other ways to layout the clusters. 

I was hoping to use AutoAnnotate followed by the CoSE layout option. With larger Networks, the CoSE is unfortunately not giving satisfying results (clusters heavily overlap).

As an alternative I thought directly using MCL clustering could work. There is an automatic layout step at the end. Unfortunately, it always uses the "pre-fused force-directed layout" without any chance to change the settings.

The best way would be to generate the layout of the cluster itself with edge-weights (so many edges between clusters would have a higher weight than fewer edges between clusters), not sure if this is possible with grouping first or so?

would be very grateful if you know any alternative ways.
thank you!

**Comment by risserlin** [comment]
This is something I struggle with all the time.  There is no perfect way to minimize the amount of reorganizing that I have to do on the resulting annotated network (and often I have do it and re-do it)
Something that sometimes helps, If you collapse the network and layout out the groups first and then expand once things are separated and clean it sometimes can help.

**Comment by pillepalle123** [comment]
hi, thy! so you run the annotation, collapse using AutoAnnotate, then you layout manually or is there a way to run a layout-algorithm? And then you expand all?
I just wish the MCLclustering would allow you to choose and set the layout it is doing at the last step...

**Comment by pillepalle123** [comment]
while we are on it. Is there a way to apply a layout algorithm within different clusters? Within clusters, the nodes mostly overlap and are not visible. Selecting hundreds of clusters separately and applying a layout for each one after another seems very heavy :)

**Comment by risserlin** [comment]
you can script it using cyrest but it won't be perfect because so much of it is visual I find.  But you can definitely grab all the clusters and apply a layout to each cluster.  If you are using R then you do it using RCy3 but if you are doing it from within cytoscape then you can write a short command script to do it.  (I generally do it from R)

**Comment by pillepalle123** [comment]
thank you! I am not too sure how to do run the command line script, so I guess I am heading for manual within Cytoscape :)

**Comment by risserlin** [comment]
In your cytoscape window at the bottom there is a command line window that you can pop up - http://manual.cytoscape.org/en/stable/Command_Tool.html

https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1758-4

I find it easier from R but you should be able to do it from command line window as well.

**Comment by pillepalle123** [comment]
thanks, the problem for me will be more R itself ;)
