### ISSUE TITLE
manually change label --> recalculate labels and loose all my changed labels

### ISSUE THREAD

**Issue by risserlin** [BaderLab/AutoAnnotateApp#163]
This is probably not a bug but more of a feature request.  After modifying labels I find words that really should be excluded from the word cloud calculation.  I add words to the exclusion list and re-calculate labels and loose all my modified labels.  It would be good to be able to keep all my manual modified labels.  (Or maybe be able to update a single label after word cloud parameter changes?

**Comment by mikekucera** [comment]
You're right, it should keep track of which labels were manually modified and prompt the user if they should be kept or overridden.
