### ISSUE TITLE
wordcloud minimum word occurrence

### ISSUE THREAD

**Issue by pillepalle123** [BaderLab/AutoAnnotateApp#164]
Hi, 
the implementation of Wordcloud is really helpful.
I was wondering if one can make use of the "minimum word occurrence" function since I don't want a label for clusters, where the word only appears once or twice.
Maybe I am not doing it right or it is generally not possible?
I changed the settings within wordcloud accordingly (setting at no clustering or clustered-standard). The wordcloud pannel is showing the results as wished (when selecting the cluster), when using autoAnnotate thought it ignores the minimum word occurrence setting?
is there a way to accomplish this?

thank you

AutoAnnotate V 1.3.3
WordCloud 3.1.3
Cytoscape 3.8.2
tested on iOS and Windows

**Comment by mikekucera** [comment]
This is a new feature request.

**Comment by pillepalle123** [comment]
thanks, I wasn't sure since the manual says that one can use the settings within wordcloud.

**Comment by mikekucera** [comment]
Depends on a commit to the WordCloudPlugin repository:

https://github.com/BaderLab/WordCloudPlugin/commit/475d51775be97f2e5928ff759d026235a5c73d66

**Comment by mikekucera** [comment]
This feature requires an updated version of WordCloud (3.1.4).

**Comment by mikekucera** [comment]
I will keep this issue open until WordCloud 3.1.4 is released.

**Comment by pillepalle123** [comment]
@mikekucera thanks for this super-fast implementation!

**Comment by pillepalle123** [comment]
@mikekucera do you happen to know when wordcloud will be released? From the release history, it seems like this might only happen every other year or so? thank you.

**Comment by mikekucera** [comment]
Hi @pillepalle123, 
Could you please do us a favour and quickly test the new versions of AutoAnnotate and WordCloud to make sure this feature works for you? Then I can upload the new versions to the Cytoscape app store and release them. 

WordCloud 3.1.4
https://github.com/mikekucera/WordCloudApp/releases/tag/v3.1.4
AutoAnnoate 1.3.4
https://github.com/BaderLab/AutoAnnotateApp/releases/tag/release%2Fv1.3.4

Just copy the jar files at those links to your `/user/CytoscapeConfiguration/3/apps/installed` folder.

The new **"minimum word occurrence"** option can be found in the **Create Annotation Set** dialog under the **Advanced** tab in the **Label Options** section.

Thank you!

**Comment by pillepalle123** [comment]
Hi @mikekucera 
Sorry for the late response! The message notification was marked as spam, so I only saw your reply today. 
But, yes, thanks so much!  just tested it and it is working perfectly. I have already started using it for my project.

**Comment by pillepalle123** [comment]
i have also seen "Allow CoSE layout to run on selected nodes." in the change log. How can I run this, didn't see it in the menu. It doesn't mean one can run the CoSE within cluster right? This would be the best combination: forced directed for clusters as it is now (since CoSE is just not working on large datasets) and CoSE for nodes within all clusters. This gives a really nice visualization. I am doing it manually for each cluster at the moment.

**Comment by mikekucera** [comment]
To run CoSE on selected nodes, first select some nodes, then go to the Main Menu and under the Layout menu select "AutoAnnotate: CoSE Cluster Layout > Selected Nodes Only"

**Comment by mikekucera** [comment]
New versions of WC and AA have been uploaded to the app store.
