### ISSUE TITLE
Collapse nework with post analysis edges - meta edges have no info

### ISSUE THREAD

**Issue by risserlin** [BaderLab/AutoAnnotateApp#165]
Created an EM with a post analysis.
Set group preferences to aggregate attributes
Collapse single node or the entire network and all post analysis edges are empty and lose their visual style.  They become black edges so they are not lost completely but you can't see any of the info associated with them.

**Comment by risserlin** [comment]
sorry. It is all edges.  Not just the post analysis edges.

**Comment by mikekucera** [comment]
Backport the changes from the enrichmentmap-service
