### ISSUE TITLE
After selecting Collapse All change Label VS to be "name"

### ISSUE THREAD

**Issue by risserlin** [BaderLab/AutoAnnotateApp#17]
After user selects collapse all change label mapping on the visual style to node name.
Is this only specific to EM though?  Not sure.

If an individual cluster is collapsed then bypass that group node to label node name.  

Is there a way to do this in the style, for a group node map label to name and for individual nodes map name to EM_gs_descr.  

Same for inverse "expand all".

**Comment by mikekucera** [comment]
I can't find any visual property for group node labels. In fact I don't think ding or the vismapper even know groups exist.

Its easy enough to set a bypass, should I just do that?

**Comment by risserlin** [comment]
NumChildren and NumDescendants are attributes specific to the group but that is it.  

Bypass is fine but with a larger network it might get messy.  Maybe when groups are created you can add an attribute "Group_label" and similar to the publication toggle you create a different style that maps to group label on the collapse.  Whatever is easier and cleaner. 

This might be a specific issue for EM though.  We use EM#_GS_Descr as the attribute to label the nodes.  Most networks probably use shared_name or name.  So it will only be an issue when the network label is not name.

**Comment by mikekucera** [comment]
I don't see an obvious solution.

I don't like option of using bypass. If most networks use "shared name" for node labels then creating a bypass to 
"shared name" or "Group_label" is redundant and confusing. And if its not what the user wants then its hard to update each group node.

Creating a new style (similar to publication toggle) is relatively easy. But I don't think it should do this automatically. Perhaps a new menu option on the AutoAnnotate panel that does this.

There is a workaround. Select the collapsed nodes (if all clusters are collapsed then select all nodes, if only some clusters are collapsed then sort the cluster table by the "collapsed" header and select the range of collapsed clusters.). Then in the first row of the node table find the "EM1_GS_DESCR" column and enter "=${shared name}". Then right click and select "apply to all rows".

Let me know if the workaround is acceptable. If not I would prefer to implement the "publication toggle" idea.

**Comment by risserlin** [comment]
Couldn't we do that from code?

When the group is created
check what attribute in the visual style the label is mapping to and set that attribute for the group node to be the group name.

**Comment by mikekucera** [comment]
Yes that can be done. There is API that lets me get the attribute name from the visual style. But it only works as long as the user doesn't switch visual styles, and it overrides the default group node aggregation behaviour. If you are ok with those caveats then I can implement this.

**Comment by risserlin** [comment]
It is something specific to EM and AA is supposed to be general.  Not sure how this will effect other peoples networks. 
Maybe pop up a warning and give the user the choice.
"Your current Style is using X for node labels.  Do you want the group names to be transferred to this attribute?"

**Comment by mikekucera** [comment]
Yes I like that
