### ISSUE TITLE
When I  create summary network, how are the resulting metanodes colored?

### ISSUE THREAD

**Issue by sylee20** [BaderLab/AutoAnnotateApp#170]
Are they colored based on average NES over all consisting nodes?
Where can I get the legend with color gradient?

**Comment by risserlin** [comment]
I believe that depends on how they are coloured in the original network.  You can directly set how the node attributes are summarized in the Group preferences pan.  ( Edit --> Preferences --> Group preferences)

<img width="962" alt="Screen Shot 2021-07-16 at 12 08 05 PM" src="https://user-images.githubusercontent.com/3842763/125977022-dc697919-20c9-44ee-a6f8-b90557361f74.png">

You can set it to take the max, min, sum value of the cluster or average.  I think by default it is set to average.  

To find the color gradient you can go to the style manager to see (or change the gradient):
<img width="456" alt="Screen Shot 2021-07-16 at 12 10 38 PM" src="https://user-images.githubusercontent.com/3842763/125977299-0dd888ad-d201-4a0f-aa81-e9f9e55c6064.png">
