### ISSUE TITLE
Summary network from Dataset coloured network

### ISSUE THREAD

**Issue by risserlin** [BaderLab/AutoAnnotateApp#172]
When you create a summary network from a network that is coloured according to dataset the resulting summary network node inherits form one of the nodes in the cluster (not sure how this is determined) but it should represent the merge of the cluster (where if one of the nodes is found in the dataset then it should be indicated as present in the summary node). 

for example - original subnetwork of summary network

![Screen Shot 2021-11-04 at 12 54 11 PM](https://user-images.githubusercontent.com/3842763/140383950-496a77cb-8663-4732-92ad-1ff4841c1ac6.png)

After merging the Dataset_Chart attribute in R and loading it back into Cytoscape as updated_Dataset_Chart:
![Screen Shot 2021-11-04 at 12 54 35 PM](https://user-images.githubusercontent.com/3842763/140384078-cd43fa5f-41a8-49b0-a1c8-3a834ef55f07.png)

There is no way to merge the Dataset_Chart attribute in the group preferences.  We can do it using RCy3 but it isn't straight forward for the no coder.

**Comment by mikekucera** [comment]
Hi Ruth,
I think I found a workaround. 
- Go to Edit > Preferences > Group Preferences. 
- Enable attribute aggregation. 
- Expand "default aggregation settings". 
- Go to "Integer list column..." and select "Maximum Value"
- Then try creating the summary network

This seems to work as expected for my quick tests.
Can you try this and let me know if it works for you?

**Comment by risserlin** [comment]
Hi Mike, 
This works. Thanks!
 i feel like this should work like this by design though.  When you collapse the network you expect that if one of the pathways in the set belonged to a certain dataset then the collapsed version will reflect this. 
Can AA collapse the dataset chart like this without requiring the user to set the aggregation setting or alternately can AA set the aggregation setting for just this attribute?

**Comment by mikekucera** [comment]
Yes, AA can ignore the group settings and do the aggregation by itself for the chart attribute.
