### ISSUE TITLE
No easy way to see the different dataset colours once created a summary network

### ISSUE THREAD

**Issue by risserlin** [BaderLab/AutoAnnotateApp#173]
Not sure if this is an AA issue or an EM issue.
Once you have created an summary network with multiple datasets in EM it is impossible to see what all the colours for the datasets refer to. the only way to bring it up is by either going to the original EM network and looking in the EM panel (can't see the panel from the collapsed network as it isn't an EM) but once you navigate to the network you can no longer see the collapsed network.  
Tried going into the style definitions but can't see which dataset is which colour from here either.

**Comment by mikekucera** [comment]
Most of the work is in EM. 
EM supports "associated" networks. Previously this was for the GeneMANIA and String networks that are created from a gene list (in the HeatMap or by right-clicking a node). I added AutoAnnotate summary networks as a new type of "associated" network. EM will show the data set colors in the EM panel for a summary network, and the heat map will work as well.
