### ISSUE TITLE
enhancement style: add different colors to ellipses

### ISSUE THREAD

**Issue by veroniquevoisin** [BaderLab/AutoAnnotateApp#176]
This is just a style suggestion and might not be important but when I format the network maps for my collaborators, they usually like it a lot when the modules are colored in different colors. I think that it might add some clarity in a complex picture.  I put some examples below. I don't know if that you could be an option added to AutoAnnotate (not the default one).
Original Style:
<img width="756" alt="Screen Shot 2022-09-21 at 1 32 33 PM" src="https://user-images.githubusercontent.com/7570379/191590374-2fabdff6-f2d7-4d9a-adde-b3a4cf26938d.png">
With colors:
<img width="601" alt="Screen Shot 2022-09-21 at 1 29 02 PM" src="https://user-images.githubusercontent.com/7570379/191590414-fd64a1ad-9688-45ad-a9cf-f036a572eeb8.png">
Another one with colors:
<img width="641" alt="Screen Shot 2022-09-21 at 2 57 32 PM" src="https://user-images.githubusercontent.com/7570379/191590448-1f571e8c-6be0-47d7-869e-26fc6a4982df.png">

**Comment by mikekucera** [comment]
Hi @veroniquevoisin, do the colors have any semantic meaning, or are they just there to help differentiate the bubbles?

**Comment by veroniquevoisin** [comment]
just to differentiate the clusters
