### ISSUE TITLE
difficulty with autoannotate after we reduced the number of enrichmentmap edges using the EM slidebar 

### ISSUE THREAD

**Issue by veroniquevoisin** [BaderLab/AutoAnnotateApp#177]
Autoannotate still considers the original number of edges even when we reduced them using the EM slide bar. I know that this is an issue that we have seen in the past and maybe not easy to resolve but I got into this problem today and I did not find it user-friend and the edge slidebar is become not useful anymore if we can't do that. I'm not sure if this is a EM and AutoAnnotate issue. My only workaround today is to filter my edges using the column filter function as I want to create subnetworks with different edge parameters.

<img width="1039" alt="Screen Shot 2022-09-26 at 11 25 50 AM" src="https://user-images.githubusercontent.com/7570379/192318330-3c091d01-57b7-4eb5-8398-e09b38d4d6af.png">

**Comment by veroniquevoisin** [comment]
It is doing it also when I filter the nodes or edges with the column filter and also when I'm creating a subnetwork. I don't think that it was doing it before.
<img width="1025" alt="Screen Shot 2022-09-26 at 1 46 17 PM" src="https://user-images.githubusercontent.com/7570379/192345264-31149a46-b35f-4505-a4ba-22757dd61dc2.png">
AutoAnnotate 1.3.5 and EnrichmentMap 3.3.4 and Cytoscape 3.9.1

**Comment by mikekucera** [comment]
Unfortunately clusterMaker does not have an option to ignore hidden nodes/edges. I have requested this feature but they have ignored my request. I could add a button to EnrichmentMap that creates a subnetwork from the visible nodes/edges, would that help?

**Comment by veroniquevoisin** [comment]
That might help: create a subnetwork when we adjust the Qvalue or edge connectivity using the slide bar

**Comment by veroniquevoisin** [comment]
As a note, I aslo have the issue when I delete nodes from the current network that I want to annotate. I'm not sure I had this issue before and if I repeat the deleting twice, AutoAnnotate does not work anymore. I'm attaching my cys file.
[J40_DNMT3B_Helena_B3_3_C3_forMike.cys.zip](https://github.com/BaderLab/AutoAnnotateApp/files/9649391/J40_DNMT3B_Helena_B3_3_C3_forMike.cys.zip)

**Comment by mikekucera** [comment]
Created new issue #178

**Comment by mikekucera** [comment]
Created new issue BaderLab/EnrichmentMapApp/issues/493

**Comment by mikekucera** [comment]
I've opened two new issues to address what has been mentioned here.

**Comment by mikekucera** [comment]
I added support for running clusterMaker on a network with hidden nodes in commit f3bb784ba7bc532b9b7760da8e0f215485e855f9. 

The way it works is to create a temporary subnetwork with just the visible nodes, then runs clusterMaker on that subnetwork, then deletes the subnetwork so the user never sees it.

However it doesn't take hidden edges into consideration. I will have to update the CreateSubnetworkTask to ignore hidden edges.
