### ISSUE TITLE
Confusing icon in AA interface

### ISSUE THREAD

**Issue by risserlin** [BaderLab/AutoAnnotateApp#18]
![aa_interface](https://cloud.githubusercontent.com/assets/3842763/12588865/b31efc8a-c428-11e5-8e76-d6814a971469.png)

There are two down arrows side by side.  Can we change one so it is visually distinct from the one next to it.  Maybe an icon with 3 or 4 parrallel lines or whatever usually indicates additional options.

**Comment by mikekucera** [comment]
It looks the same as the Select tab, that's why I did it that way.

**Comment by risserlin** [comment]
It is still confusing.  It is more pronounced in AA because the buttons are closer together and smaller.  Can we change it to something like this icon:
![1454037977_menu-alt](https://cloud.githubusercontent.com/assets/3842763/12659290/0fb5534a-c5dc-11e5-8fc5-b04d34cd5431.png)

**Comment by mikekucera** [comment]
Sure, that icon is part of font awesome so we can use it.

**Comment by mikekucera** [comment]
Fixed by f810dec8b0def260a3bf64256fc7cbe2812a099c
