### ISSUE TITLE
Is there a toggle to turn on and off connection between annotations and clusters?

### ISSUE THREAD

**Issue by risserlin** [BaderLab/AutoAnnotateApp#185]
If node movement is no longer firing events to update the annotations is there a toggle to turn it off and on to get that connections working again?

Was this a bug in a previous release of Autoannotate?  (I remember having this issue in the past and I think I used to save my session and then re-start to get the desired behaviour back but I am not sure)

**Comment by mikekucera** [comment]
I believe the issue was the user didn't know how to select a cluster. I will update the docs to better explain the process.
