### ISSUE TITLE
annotation sets created in 1.3.5 are incomplete once updating to 1.4.0

### ISSUE THREAD

**Issue by Andre-C-M** [BaderLab/AutoAnnotateApp#197]
amazing, very useful app!
I generated annotation sets (a few hundred annotations each) with version 1.3.5. After updating to 1.4.0 selecting them only restores an incomplete subset of those annotations (labels and shapes). Reinstalling 1.3.5. fixes the issue and all labels are fully displayed.

using Cytoscape 3.10 
(files initially generated in 3.9.1, but that doesn't seem to be relevant since it behaves the same with this version)

**Comment by mikekucera** [comment]
would you be able to send me a copy of your session file?

**Comment by Andre-C-M** [comment]
sure, thank u very much. I have sent you the session file.

**Comment by mikekucera** [comment]
Bug appears to have been caused by commit 37b1441b5f05569c0aff418367938e782f592bde
