### ISSUE TITLE
Label font size when creating a subnetwork

### ISSUE THREAD

**Issue by veroniquevoisin** [BaderLab/AutoAnnotateApp#200]
The label font size (most significant geneset for each cluster has larger font size) is very good and enhances clarity. However, it  stays on a subnetwork where it does not make sense anymore. What could be the solution? Can the clustering and style be reapply on a subnetwork? or style earased? or can we call it from Autoannote?

Example of a subnetwork:
<img width="1087" alt="Screenshot 2024-01-31 at 4 25 34 PM" src="https://github.com/BaderLab/EnrichmentMapApp/assets/7570379/d68ff7fd-3ea9-4583-8b49-a69465d362af">

**Comment by mikekucera** [comment]
Commit e4ea0a024573467f0c0d14102d463d6c0a95859c

**Comment by mikekucera** [comment]
I update AA so that when creating a subnetwork it doesn't copy the style bypasses for the highlighted nodes.
I added a button to the EM main panel that lets you apply the significance highlight again, this can be run on the subnetwork to highlight nodes.
