### ISSUE TITLE
enhancement: add option to label modules using the most significant genesets

### ISSUE THREAD

**Issue by veroniquevoisin** [BaderLab/AutoAnnotateApp#201]
Not sure if it exists or not. Is it possible to set the module labels using the most significant geneset instead of the most frequent word? To have the choice for users who would have this preference. 
I have noticed that when I edit the labels, I usually use this most significant node as reference. 

Then we could summarize the map using this gene-set only to create a subnetwork and do a bargraph in a "ClusterProfiler" stlye to be exported as pdf.

Before editing the label:

**Comment by mikekucera** [comment]
This is available in the "Label Options" section of the dialog.

<img width="603" alt="Screenshot 2024-02-29 at 2 03 09 PM" src="https://github.com/BaderLab/AutoAnnotateApp/assets/5350528/825b02de-debf-48d9-91fe-f34b7acdb525">
