### ISSUE TITLE
blank AA Display

### ISSUE THREAD

**Issue by veroniquevoisin** [BaderLab/AutoAnnotateApp#202]
While creating a map, I got a blank AutoAnnotate Display. 
It was different from the frozen display as it was not flickering.
I tried to unpin/pinbut it did not work.
Then I decided to redraw the annotation, I got an error message that I needed to use clusterMaker app set to none for the edge weight and it worked. Not sure if related to the blank issue.
<img width="884" alt="Screenshot 2024-02-28 at 9 22 33 PM"
<img width="997" alt="Screenshot 2024-02-28 at 9 22 28 PM"
<img width="829" alt="Screenshot 2024-02-28 at 9 21 44 PM" src="https://github.com/BaderLab/AutoAnnotateApp/assets/7570379/d1b7744d-a0b8-4517-bdf4-71d0128db82a">
src="https://github.com/BaderLab/AutoAnnotateApp/assets/7570379/bfacc7ff-14df-4f22-ad38-395a511ecec8">
src="https://github.com/BaderLab/AutoAnnotateApp/assets/7570379/81d6a85e-ccb0-483f-8a6e-64530d4b607a">

**Comment by veroniquevoisin** [comment]
<img width="997" alt="Screenshot 2024-02-28 at 9 22 28 PM" src="https://github.com/BaderLab/AutoAnnotateApp/assets/7570379/73c19634-59d1-4946-a2c3-da7c07f40ad7">

**Comment by mikekucera** [comment]
Hi Veronique,
I'm going to need the session file or data files to try to reproduce this. Could you also please send your framework.log file because that might have an error trace in it.

**Comment by veroniquevoisin** [comment]
I was able to reproduce and caught the error on the log:


![Screenshot 2024-03-01 at 4 21 30 PM](https://github.com/BaderLab/AutoAnnotateApp/assets/7570379/a9241f03-fd1e-4f9a-a510-68f8dc93cfff)




![Screenshot 2024-03-01 at 4 21 39 PM](https://github.com/BaderLab/AutoAnnotateApp/assets/7570379/8add5590-ca96-48ec-85c8-b42db9ae5ca3)

**Comment by mikekucera** [comment]
Hi Veronique, I'm not sure what's going on here. I'm not able to reproduce this issue with the session file you sent.

The screenshot of your log file says that the 'similarity_coefficient' column of the 'basalA.GseaPreranked' node table is missing. The session file you sent me doesn't have a network named 'basalA.GseaPreranked'.

Do you remember exactly what you were doing when you encountered this bug? Are you still able to reproduce it?

**Comment by veroniquevoisin** [comment]
It happens when I create a map with GSEA result from 1 data that I have.
Here is the session that I just redid. I just created the map with the one dataset.
https://www.dropbox.com/scl/fi/vjkzj53r0e98md7tihp2u/testmikeMAr11.cys?rlkey=vpd01qbx45is4bm674hm1xt5c&dl=0

**Comment by veroniquevoisin** [comment]
<img width="1291" alt="Screenshot 2024-03-11 at 12 28 01 PM" src="https://github.com/BaderLab/AutoAnnotateApp/assets/7570379/b95b5d2f-5c35-4c6c-998c-fbb45bc4c359">

**Comment by mikekucera** [comment]
So the error happens while creating the enrichment map network, right? Not when creating annotations after the network has already been created.
If so can you please send me the data files you used to create the network. Thanks.

**Comment by veroniquevoisin** [comment]
yes correct
here is the gsea result: https://www.dropbox.com/scl/fo/7qnhc6qxilyjcgkeueb8r/h?rlkey=udhvdtzrw9wnckvimjrihx4cd&dl=0
The issue is only with classicB

**Comment by veroniquevoisin** [comment]
I got the issue again with gprofiler results with latest builts of AA and EM


![Screenshot 2024-03-12 at 11 35 02 AM](https://github.com/BaderLab/AutoAnnotateApp/assets/7570379/ef13922f-251d-4381-9c1d-27b5fefcf7ce)

**Comment by veroniquevoisin** [comment]
Do you think that the default should be? Although I can see that with this option, we can't control the number of clusters. Can you do that from clustermaker MCL granularity parameter? 
![Screenshot 2024-03-12 at 11 33 01 AM](https://github.com/BaderLab/AutoAnnotateApp/assets/7570379/6625a9dd-c793-4bee-aa5f-7120c60a71e1)


![Screenshot 2024-03-12 at 11 37 33 AM](https://github.com/BaderLab/AutoAnnotateApp/assets/7570379/77f8a0ab-63e9-49c2-a02d-d8de50732108)

**Comment by veroniquevoisin** [comment]
gprofiler file that Iused:
[gProfiler_hsapiens_3-12-2024_11-06-35 AM.gem.txt](https://github.com/BaderLab/AutoAnnotateApp/files/14575047/gProfiler_hsapiens_3-12-2024_11-06-35.AM.gem.txt)

**Comment by veroniquevoisin** [comment]
closed and opened Cytoscape and it worked:

![Screenshot 2024-03-12 at 12 09 24 PM](https://github.com/BaderLab/AutoAnnotateApp/assets/7570379/28faa6b9-37d9-4eae-bbb0-1934f67fda11)

**Comment by mikekucera** [comment]
Your latest error log screenshot is interesting. I noticed it says it can't find the 'similarity_coefficient' column in the **node** table, of course it can't its in the edge table.
Could you please send me your framework.log file. I'm starting to think this is a bug in clusterMaker.

**Comment by veroniquevoisin** [comment]
here is one session :https://www.dropbox.com/scl/fi/ybdktw0ecnby12iaa9q1h/testmikeMAr12.cys?rlkey=fw5e2cdqwivd1vet5u8xqpwv0&dl=0

**Comment by veroniquevoisin** [comment]
![Screenshot 2024-03-12 at 2 43 52 PM](https://github.com/BaderLab/AutoAnnotateApp/assets/7570379/ceef701d-50c6-4fcf-b8ea-96de3e2862a8)

**Comment by veroniquevoisin** [comment]
Where can I find the framework.log file?

**Comment by mikekucera** [comment]
In the `<user-home>/CytoscapeConfiguration/3` folder, its called `framework-cytoscape.log`

**Comment by veroniquevoisin** [comment]
[framework-cytoscape.log](https://github.com/BaderLab/AutoAnnotateApp/files/14577239/framework-cytoscape.log)

**Comment by veroniquevoisin** [comment]
here it. is

**Comment by mikekucera** [comment]
I think we are running into this bug in clusterMaker: https://github.com/RBVI/clusterMaker2/issues/10

The issue is that the MCL command remembers the range of values used for the edge attribute. If you run the MCL command a second time on a different network or attribute it does not update the range properly. This can lead to an exception.

I don't think the bug in clusterMaker is going to be fixed (its been open since 2017). I thought I had already found a way of working around the bug, but now its showing up again. I'll have to figure out why and maybe find a new way of working around it.

Another option would be to use a different clustering algorithm as the default. I think everyone is happy with MCL so I'll take a stab at fixing this first.

**Comment by mikekucera** [comment]
I removed the use of the cutoff parameter.
ba4a9beaf948c8ffc080744ab442b22eb93399c3
