### ISSUE TITLE
Hightlight significant node on a subnetwork: it works well!

### ISSUE THREAD

**Issue by veroniquevoisin** [BaderLab/AutoAnnotateApp#204]
I tried the option "highlight significant node " on a subnetwork and it worked well. It really complements the ellipse label. Thanks!
<img width="235" alt="Screenshot 2024-03-27 at 8 49 32 AM" src="https://github.com/BaderLab/AutoAnnotateApp/assets/7570379/18f4a4b1-42e6-4d52-af82-e6bb8e6e8f18">

<img width="1049" alt="Screenshot 2024-03-27 at 8 11 33 AM" src="https://github.com/BaderLab/AutoAnnotateApp/assets/7570379/4d14fbc8-63c9-42ce-b495-0e2b2d0707cb">

**Comment by mikekucera** [comment]
Great!
