### ISSUE TITLE
Collapse All performance

### ISSUE THREAD

**Issue by mikekucera** [BaderLab/AutoAnnotateApp#27]
The performance of the "collapse all" command is slow on large networks with lots of clusters. 

This is likely a problem with the groups implementation.

**Comment by risserlin** [comment]
painfully slow! Considering this won't be fixed any time soon can we add an option to create a subnetwork of the "collapsed nodes" so user can quickly examine overall themes without waiting 10+min to collapse and then re-expand.

**Comment by mikekucera** [comment]
Note to self: Try using YourKit to profile node collapsing.

**Comment by mikekucera** [comment]
This has to get fixed in Cytoscape... if it ever gets fixed.

Taking it off the v1.1.0 Milestone.

**Comment by mikekucera** [comment]
Summary network has been implemented, and collapsing is somewhat faster in newer versions of Cytoscape. If collapsing performance ever gets better it will have to be done in Cytoscape. Going to close this issue.
