### ISSUE TITLE
collapse all get node labels correct but collapsing an individual node gets it wrong

### ISSUE THREAD

**Issue by risserlin** [BaderLab/AutoAnnotateApp#43]
If I collpase the entire network the node labels of the collapsed node are set to the label on the cluster.  If I then expand and collapse an individual node the collapsed node sets the label to whatever the visual style defines as the label.  (In this example it is EM_Descr which contains the concatenated list of all nodes labels)

Happened in cytoscape 3.3 using AA 53b03c0cc91dbc8824a1ea97ac1324c48679e2e7  ( I don't know if this is RC3 or RC4)

**Comment by mikekucera** [comment]
Can't reproduce, must be fixed.
