### ISSUE TITLE
Hide annotation if all nodes are hidden

### ISSUE THREAD

**Issue by risserlin** [BaderLab/AutoAnnotateApp#47]
When creating figures often only want to focus on one section.  I hide large sections of the nework in order to create the figure but the annotations are still there. It would be good if an annotation can be automatically hidden if all of its members are hidden.

**Comment by mikekucera** [comment]
The cluster annotations now respond properly to nodes being hidden/shown.
However, the cluster label does not update. The label is still generated from all the nodes in the cluster even if they are hidden. Let me know if you would like me to change that behaviour, but there may be performance issues with regenerating the labels.
