### ISSUE TITLE
Modify multiple annotations together

### ISSUE THREAD

**Issue by dhollan9** [BaderLab/AutoAnnotateApp#48]
Suggested enhancement: It would be convenient if you could modify the shape and color of multiple annotations at once. As it stands, you can change the opacity, the border width, and toggle between rectangle and ellipse shaped annotations. You have to change each annotation one by one if you want to use a different shape (e.g. rounded rectangle) or color.

**Comment by mikekucera** [comment]
Duplicate of https://github.com/BaderLab/AutoAnnotateApp/issues/39
