### ISSUE TITLE
changing network doesn't refresh AA table

### ISSUE THREAD

**Issue by risserlin** [BaderLab/AutoAnnotateApp#49]
when I go from an annotated network to one that is not annotated the annotations are still viewable in the autoannotate panel (tried in cytoscape 3.4)

**Comment by mikekucera** [comment]
This sounds like the bug I released version 1.0.1 to solve. Do you have the latest bug-fix version (1.0.1) from the app store?

**Comment by risserlin** [comment]
I must have been using 1.0.0 (or it is something specific to my windows).  Works fine with 1.01 on Mac.

**Comment by mikekucera** [comment]
Great, thanks.

**Comment by mikekucera** [comment]
Fixed in commit c19a06507fa9b64b34189c53e41679bfa80f3001
