### ISSUE TITLE
Data reproducibility issue

### ISSUE THREAD

**Issue by risserlin** [BaderLab/AutoAnnotateApp#50]
No way of knowing parameters used to create annotation set on saved or previous session.  
(parameters needed - any that modify the resulting annotations for instance, clustering algorithm used (can be deduced from node attribute but what if user had tried multiple clustering algorithms and settles on one), wordcloud normalization factor, attribute used to create labels, additional delimiters, or additional excluded words....)

Even knowing the above parameters there is no way to figure out manual modifications.  (Maybe just a flag saying there are additional modifications?)  

Viewing them in the Result panel similar to how we can do it in EM.

**Comment by mikekucera** [comment]
This would be relatively easy to do if the parameters were saved per-cluster. The results would be verbose, but accurate. I could add an button or menu item somewhere called "view creation parameters". That would pop-up a dialog with a table that listed all the clusters and the creation parameters for each cluster. The table would have the ability to sort columns. Is that ok with you?

**Comment by risserlin** [comment]
I was thinking of something more global.  A little text box in the results panel that just list the parameters (by default it is collapsed but users can expand).  It would be cumbersome to check every cluster.
AA params - 
cluster algorithm: MCL 
Edge weight column:
label column:
Label algorithm:
...
WordCloud params:
Normalize - 
(add any flags that are different from the default)

**Comment by mikekucera** [comment]
Ok, but if the user makes manual edits those initial parameters won't apply to the clusters that were edited. 

Also I think to get the wordcloud parameters (normalization) I need to update WordCloud to return that info.
