### ISSUE TITLE
create subnetwork from AA looses all annotations

### ISSUE THREAD

**Issue by risserlin** [BaderLab/AutoAnnotateApp#59]
When creating a subnetwork form an annotated network the subnetwork doesn't have the annotations.  Can't simply just add annotations to subnetwork because result would be different (only if you are using wordcloud normalization) because the network used to calculate the background is a lot smaller. 

I think there should be an option when creating a subnetwork - would you like to transfer annotations to new subnetwork? There can be some cases where you want to have the annotations and other where you don't.

**Comment by mikekucera** [comment]
This is now supported with the "Copy Annotation Sets from Network..." option.
