### ISSUE TITLE
Add Autoannotate commands

### ISSUE THREAD

**Issue by risserlin** [BaderLab/AutoAnnotateApp#68]
Add autoannotate commands so we can annotate a network through cyrest.

**Comment by jooolia** [comment]
Was just about to open this issue. This would be very helpful!

**Comment by risserlin** [comment]
Hi Julia, 
This was just added last week.  There is no build with it yet but here is a link to a build with it:
https://www.dropbox.com/s/c6g78vocljbn498/autoannotate-1.2.0-SNAPSHOT.jar?dl=0

Available commands:
  autoannotate label-clusterBoosted  Run label algorithm 'clusterBoosted'. Uses WordCloud to calculate the labels. Words in the label are the most frequent words and their adjacent words. The higher the "adjacent word bonus" is, the more likely adjacent words will be in the label.
  autoannotate label-sizeSorted  Run label algorithm 'sizeSorted'. Uses WordCloud to calculate the labels. Words in the label are the most frequent words.

autoannotate label-clusterBoosted arguments:
adjacentWordBonus=<int>: Size bonus given to words that are adjacent to the largest words. Default: 8
labelColumn=<String>: Name of node column to use to generate the labels
maxWords=<int>: Max words to include in label. Default: 4
nodeList=[nodeColumn:value|node name,...]|all|selected|unselected: List of nodes in the cluster

**Comment by jooolia** [comment]
neat! Thanks I will give it a whirl!

**Comment by jooolia** [comment]
Thanks! It is working and able to find the commands, but I am running into a small issue. When I "GET" the desired url I get a response that it has worked (200), but I do not see any response in my cytoscape window.

To illustrate I GET the following url:

```
http://localhost:1234/v1/commands/autoannotate/label-clusterBoosted?adjacentWordBonus=8&labelColumn=EM10_GS_DESCR&maxWords=30&nodeList=all
```

and get the following response with no change in Cytoscape. 

```
Response [http://localhost:1234/v1/commands/autoannotate/label-clusterBoosted?adjacentWordBonus=8&labelColumn=EM10_GS_DESCR&maxWords=30&nodeList=all]
  Date: 2016-08-05 07:51
  Status: 200
  Content-Type: text/plain
  Size: 10 B

Finished
```

Is there something obvious that I missed? Thanks for any help or hints. :bowtie:

**Comment by risserlin** [comment]
Hi Julia, 
Are there any commas in any of your node names?  I calculate the annotations for a bunch of clusters and everything returns an annotation except the one group where one of the node names has a comma.

Also, this command only returns the annotation label it does not add the annotation to the network.  We either need to add a flag to the command to do this or have an additional command to that.  I'll add a feature request.

**Comment by jooolia** [comment]
Hi Ruth,

Thanks for the reply! The node names were GO terms and do not contain commas. 

Good to know that it only returns the label. Neither via the command line interface nor using cyREST  am I able to see the label annotations in the node table when I run the command. 

I will try to make a small reproducible problem to better illustrate what I am seeing (and maybe I will solve my own problem).

**Comment by risserlin** [comment]
Hi Julia, 
Sorry.  There is an omission in my previous post.  Autoannotate will not be able to find node names that have quotes or colons.  I actually changed my commands to look for nodes by a different attribute (in my  case EM_GS_DESCR) than name because all my names have colons in them.  

for example command:
autoannotate label-clusterBoosted maxWords=3 labelColumn="EM1_GS_DESCR" nodeList="EM1_GS_DESCR:organelle fission,EM1_GS_DESCR:nuclear division,EM1_GS_DESCR:mitotic nuclear division,EM1_GS_DESCR:M Phase,EM1_GS_DESCR:chromosome segregation,EM1_GS_DESCR:sister chromatid segregation"
→ nuclear division segregation
SUCCEEDED

the label won't appear in the node table.  It will only appear in the response from the command.

**Comment by jooolia** [comment]
Thanks Ruth! That is helpful! I will give that a try.

**Comment by mikekucera** [comment]
Commands added in commit 6297679206d0026522778ea4914d6114929d4536
