### ISSUE TITLE
Add option to create annotation to auto annotate command

### ISSUE THREAD

**Issue by risserlin** [BaderLab/AutoAnnotateApp#69]
maybe as a flag on the current autoannoate command.

**Comment by mikekucera** [comment]
This will be a new command that fully annotates the network.

**Comment by risserlin** [comment]
Any ETA on this command?  This is the only piece missing from the EM pipeline.  (might be helpful for the cyrest workshop)

**Comment by mikekucera** [comment]
I've been focusing entirely on EM, but I can bump up the priority on this. There is a long list of bugs/enhancements for AA 1.2 though. I guess I could make a custom build for the workshop.

**Comment by risserlin** [comment]
![image](https://cloud.githubusercontent.com/assets/3842763/26735655/d24147b6-4790-11e7-8f33-35d8ade9af00.png)
Does the bolded parameters mean that it is required?

When I try to run the command I get the following error:
Failed: The cluster algorithm MCL Cluster requires the 'edgeWeightColumn' parameter.

Can AA have a default for MCL.  I have many networks and figuring out which column is the similarity coeff will require a few additional cyrest calls.  Is there a way to do it from AA instead.

**Comment by mikekucera** [comment]
Yes labelColumn is required.

No problem for providing default for edgeWeightColumn.

**Comment by mikekucera** [comment]
I added reasonable defaults for EM networks for the **labelColumn** and **edgeWeightColumn** arguments.
