### ISSUE TITLE
Annotate individual cluster in network

### ISSUE THREAD

**Issue by risserlin** [BaderLab/AutoAnnotateApp#70]
Without creating a new annotation set I just want to annotate a select few clusters
highlight an individual cluster
Right click to get context menu, go to Apps->autoannotate->Create clutser and nothing happens.  

I don't think this functionality is there yet but would be nice to be able to annotate individual selection without creating an annotation set.

**Comment by risserlin** [comment]
I could hack it for now.
Create dummy attribute which contains the a cluster number for just the subset I want to annotate and then create an annotation set based on that dummy attribute

**Comment by mikekucera** [comment]
You can't have a cluster without it being part of an annotation set. However, I can change it so that if you create a cluster using the context menu and there is no current annotation set it will automatically create one and add the cluster to it.

**Comment by risserlin** [comment]
That sounds good.  Where would this option be in the context menu though?  Aren't the context menus divided by apps?  Also, isn't the context menu for an individual node as opposed to cluster of nodes?
Couldn't this fall under the solution for #88

**Comment by mikekucera** [comment]
You select some nodes then right click anywhere on the network. It would be under the Apps submenu.

**Comment by risserlin** [comment]
Apps -> AutoAnnotate -> createcluster?
It is already there.  (But doesn't seem to do anything)
![screen shot 2017-07-12 at 3 47 02 pm](https://user-images.githubusercontent.com/3842763/28136938-65fc1024-6719-11e7-8ba6-e7157744dfd5.png)

**Comment by mikekucera** [comment]
One complication. We require the user to select which column to use for labels. There are two options:
1) Use the "EM1_GS_DESCR" column by default, if it doesn't exist use the "name" column.
2) Show a pop-up dialog allowing the user to choose the column.

I'm in favour of option 1, if the user wants any options at all they can create the annotation set the normal way.

**Comment by mikekucera** [comment]
Yeah it only does something if you have an annotation set selected.

**Comment by risserlin** [comment]
Option 1 is fine.  The assumption is that users are going to annotated enrichment maps and if they aren't the field they want to use will likely be the name.  Not guarenteed though.
 Could you also add a preference somewhere so they can change the default? (Maybe a future feature)

**Comment by mikekucera** [comment]
sure
