### ISSUE TITLE
labels not aligned with ellipses/rectangles after unchecking scale font by cluster

### ISSUE THREAD

**Issue by veroniquevoisin** [BaderLab/AutoAnnotateApp#71]
labels not aligned with ellipses/rectangles after unchecking scale font by cluster. It is recentered  after redrawing the labels.
trying to attach pictures": 
picture 1: original auto annotation
picture 2: Scale font by cluster
picture 3: labels are centered again after redrawing the annotations
![pictrue3](https://cloud.githubusercontent.com/assets/7570379/18788048/60c35bf8-8173-11e6-963d-8214301de86c.png)
![picture1](https://cloud.githubusercontent.com/assets/7570379/18788046/60bec566-8173-11e6-9d4e-48e2aab8cdfb.png)
![picture2](https://cloud.githubusercontent.com/assets/7570379/18788047/60bf1278-8173-11e6-83f8-fc25ee800acc.png)

**Comment by veroniquevoisin** [comment]
![picture1](https://cloud.githubusercontent.com/assets/7570379/18788214/0932f0fa-8174-11e6-8807-6c795fae57ff.png)
![picture2](https://cloud.githubusercontent.com/assets/7570379/18788215/093b108c-8174-11e6-8084-1b3d2db936c8.png)
![pictrue3](https://cloud.githubusercontent.com/assets/7570379/18788216/0947b170-8174-11e6-948f-b29dae325df5.png)
pictures with numbers

**Comment by mikekucera** [comment]
This is working now.
