### ISSUE TITLE
enhancement: be able to save an autoannoted collapsed network (.cys file)

### ISSUE THREAD

**Issue by veroniquevoisin** [BaderLab/AutoAnnotateApp#74]
enhancement: be able to save an autoannoted collapsed network (.cys file)
(not sure where I should post it: Cytoscape, AA or EM)
currently the collapsed network expands when I try to save the file
AA v1.0.0-SNAPSHOP and cytoscape 3.3.0

**Comment by risserlin** [comment]
Hi Veronique, 
There is feature (not sure in which version it is in) but instead of expanding and collapsing the network you can create a summary network which is basically the collapsed version of the network.  If you create the summary network save won't expand everything.
