### ISSUE TITLE
do autoannotate cluster/annotate hidden nodes?

### ISSUE THREAD

**Issue by veroniquevoisin** [BaderLab/AutoAnnotateApp#78]
in enrichmentmap : moved the qvalue slide from 0.05 to 0.01 to get less nodes on the map , reapplied an organic layout.
clusters bigger than expected appeared: do autoannotate annotate hidden nodes? 
![screen shot 2017-01-19 at 3 06 21 pm](https://cloud.githubusercontent.com/assets/7570379/22123321/39a3a86e-de59-11e6-93e9-a17e33623c4e.png)

**Comment by mikekucera** [comment]
Yes it is, and there's nothing I can do about it because clusterMaker doesn't ignore hidden nodes. You can just create another subnetwork consisting of the visible nodes before running AA.
