### ISSUE TITLE
create summary network - missing singletons

### ISSUE THREAD

**Issue by risserlin** [BaderLab/AutoAnnotateApp#81]
When creating a summary network through auto-annotate only the clusters are summarized.  The singletons do not get transferred to the new network.

**Comment by risserlin** [comment]
work around  - manually add cluster numbers to each of the singletons and re-create annotation, then create summary network.

**Comment by mikekucera** [comment]
Duplicate of #65

**Comment by mikekucera** [comment]
Duplicate of #65
