### ISSUE TITLE
Exclude post analysis edges and nodes from annotation calculation

### ISSUE THREAD

**Issue by risserlin** [BaderLab/AutoAnnotateApp#88]
If you annotate your network after you have run post analysis clusters can appear that weren't previously there (and don't really make sense). 

Can you have an advanced option (that is by default selected) to excluded post analysis nodes and edges from cluster calculation and auto annotation.  I know that it is specific to EM but it would make automation pipelines much better.

**Comment by risserlin** [comment]
But, if i could add annotations using a command prior to running a post analysis then this wouldn't be an issue.  see #69

**Comment by mikekucera** [comment]
I see no problem adding this feature. We already detect EM networks and
suggest using the description column for labels instead of the name column.

**Comment by mikekucera** [comment]
How about a new option "annotate selected nodes only". Then you would select all the non post analysis nodes before creating the annotation set.

It would be slightly more cumbersome because of the additional selection step, but it would be more general purpose, and perhaps also useful for people not using EM.

**Comment by risserlin** [comment]
That is fine with me.

**Comment by mikekucera** [comment]
Well that's not going to work. Turns out clusterMaker is totally broken when running on selected nodes only. 

Back to the original plan, run clusterMaker on the entire network then remove post analysis nodes from the clusters.

**Comment by risserlin** [comment]
Are you sure?  I am pretty sure I have used clustermaker on selected only.

**Comment by mikekucera** [comment]
Yes it works the first time. But all subsequent calls to the mcl command always run on the same set of nodes as the first call. So if you change the selection it still runs on the original selected nodes.

**Comment by mikekucera** [comment]
https://github.com/RBVI/clusterMaker2/issues/8

**Comment by mikekucera** [comment]
This is basically fixed along with #29, but there are a couple quick steps that need to be taken.

- Deselect the PA data sets in the EM control panel. This causes them to become hidden.
- Create an annotation set. The hidded PA nodes will be ignored during the cluster calculation.
- Re-select the PA data sets in the EM control panel.
