### ISSUE TITLE
different defaults when running aa from the command line

### ISSUE THREAD

**Issue by risserlin** [BaderLab/AutoAnnotateApp#89]
With the command this network is annotated as:
![image](https://cloud.githubusercontent.com/assets/3842763/26739738/04b30af8-47a1-11e7-82a7-610d9e48a250.png)

From the interface the exact same network is annotated as:
![image](https://cloud.githubusercontent.com/assets/3842763/26739755/17f14eea-47a1-11e7-9b6d-fc9865a67a8e.png)

**Comment by risserlin** [comment]
for both the command and interface the only parameter I changed was to set the maxword cutoff to 3

**Comment by mikekucera** [comment]
The networks in the images don't look the same, the node labels are different.
I verified that the parameters coming from the UI and the command are the same. 
Can you double check please.

**Comment by risserlin** [comment]
Networks are exactly the same but I didn't want to compute the name parameter so I just used name which would be the same for every network.  So this is related to the previous issue that is now resolved.

**Comment by mikekucera** [comment]
Can you send me the session file please. I'm worried this might actually be
an issue with word cloud.

**Comment by mikekucera** [comment]
Hi Ruth, can you send me the session file please.

**Comment by risserlin** [comment]
With the latest version that chooses the correct column automatically this isn't a problem anymore.  I sent a session file to you.

**Comment by mikekucera** [comment]
Oh ok, can I close this issue then?

**Comment by mikekucera** [comment]
Thanks!
