### ISSUE TITLE
Autoannotate command with network specified but network is not current network returns error

### ISSUE THREAD

**Issue by risserlin** [BaderLab/AutoAnnotateApp#91]
When running the aa command specifying the network you want to run aa on using "network = network_name" parameter.  If the network is not the current network then the command returns 500 error and in the browser the error message is: "Failed: unrecognized (table entry): Node suid: 140  (table name): USER"

**Comment by mikekucera** [comment]
Sigh. Unfortunately clusterMaker is really buggy around this. The clusterMaker commands have a 'network' argument but it doesn't work properly, it tries to cluster the wrong network, then when wordcloud runs it gets passed the clusters from the wrong network.

The only way I can see to work around this is to globally set the current network to be the one specified in the aa command's "network" argument before running clusterMaker. Ruth, do you think that would be a problem?

**Comment by risserlin** [comment]
I got around it by running aa right after I created the network as opposed to go through each of the created network afterwards and annotating them.  

When you say set the network globally do you mean change the current network to the network you are running the command on?  (that was basically my work around.) . As long as I don't have to make an extra call to select the correct network it is fine with me.

**Comment by mikekucera** [comment]
That's right. Thanks.
