### ISSUE TITLE
annotations are sporadically and randomly placed in far corners of pane 

### ISSUE THREAD

**Issue by risserlin** [BaderLab/AutoAnnotateApp#93]
annotations are sporadically and randomly placed in far corners of pane 

using version 1.2 and cytoscpae 3.5.1.  I thought this issue was fixed?

**Comment by mikekucera** [comment]
No this is a bug in Cytoscape. I have no idea why its happening.

**Comment by risserlin** [comment]
I thought this was supposed to be fixed in Cytoscape 3.5

**Comment by mikekucera** [comment]
This has been fixed in Cytoscape 3.6.
https://code.cytoscape.org/redmine/issues/3980
