### ISSUE TITLE
It would be nice to allow any column to be the label column

### ISSUE THREAD

**Issue by mcsimenc** [BaderLab/AutoAnnotateApp#96]
Hi! 

I have a network that has a column that has the labels I want to use for AutoAnnotate but it is not selectable in Label Options: Label Column

It would be great if someone could allow any column to be the "Label Column"!

**Comment by risserlin** [comment]
Any String column should be allowed.  Is your column of type string?

**Comment by mcsimenc** [comment]
Nope it's an integer. Thanks! I can fix it.
